version: '3.8'
services:

  nextapp:
    build:
        context: ./
        dockerfile: Dockerfile
    
    ports:
      - "80:80"
    volumes:
      - ./build:/build
    container_name: nextapp
    networks:
      - front-tier

networks:
  front-tier:
